//! BusyBox / SysV init (non-systemd Linux) service backend.
//!
//! Active when the host does *not* run systemd — e.g. the Sipeed NanoKVM and
//! other buildroot/BusyBox embedded devices. Their init (`/sbin/init` →
//! busybox) runs every executable `/etc/init.d/S??*` script in numeric order
//! with a `start` argument during boot (driven by `/etc/init.d/rcS`), so
//! installing an `S96iroh-tunnel-<role>` script here is all that is needed for
//! boot-time autostart.
//!
//! The script manages the daemon with a plain background launch + PID file — no
//! `start-stop-daemon` dependency, so it works on the leanest BusyBox config.
//! iroh-tunnel traps SIGTERM for a graceful drain, which `stop` honours before
//! falling back to SIGKILL after a 5 s grace window.
//!
//! Boot order `S96` deliberately runs *after* networking and the host stack:
//! on the NanoKVM, `S40network` and `S95nanokvm` precede it, so the tunnelled
//! targets exist before iroh-tunnel binds/dials.
//!
//! Scope: BusyBox init is system-wide only (no per-user domain exists), so
//! both System and User scopes install to `/etc/init.d` — User scope prints a
//! note rather than failing. Requires root.

use super::{resolve_binary, ServiceScope};
use anyhow::{bail, Context, Result};
use std::path::{Path, PathBuf};

/// Boot-order prefix. BusyBox init runs `/etc/init.d/S*` sorted numerically, so
/// `S96` starts iroh-tunnel after the host stack is up (see module docs).
const START_ORDER: u8 = 96;

/// `/etc/init.d/S96iroh-tunnel-<role>` — the name busybox init auto-starts.
fn script_name(role: &str) -> String {
    format!("S{START_ORDER}iroh-tunnel-{role}")
}

/// Where the init script lives. BusyBox init scans `/etc/init.d`, so this is
/// fixed — there is no scope/per-user variant on a non-systemd host.
fn script_path(role: &str) -> PathBuf {
    PathBuf::from("/etc/init.d").join(script_name(role))
}

/// Render the BusyBox/SysV init script body for `iroh-tunnel {role} run`.
///
/// Pure function (no I/O) so the template can be unit-tested without touching
/// the filesystem. Paths are embedded verbatim inside double quotes; system
/// paths never need shell escaping in practice.
fn format_script(role: &str, binary: &Path, config: &Path) -> String {
    let binary = binary.to_string_lossy();
    let config = config.to_string_lossy();
    let pidfile = format!("/var/run/iroh-tunnel-{role}.pid");
    let logfile = format!("/var/log/iroh-tunnel-{role}.log");
    format!(
        r#"#!/bin/sh
# Auto-generated by `iroh-tunnel service install` — do not edit by hand.
# BusyBox/SysV init script for iroh-tunnel ({role}).

DAEMON="{binary}"
ROLE="{role}"
CONFIG="{config}"
PIDFILE="{pidfile}"
LOG="{logfile}"

start() {{
    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE" 2>/dev/null)" 2>/dev/null; then
        echo "iroh-tunnel ($ROLE) already running (pid $(cat "$PIDFILE"))"
        return 0
    fi
    echo "Starting iroh-tunnel ($ROLE)"
    "$DAEMON" "$ROLE" run --config "$CONFIG" >> "$LOG" 2>&1 &
    echo $! > "$PIDFILE"
}}

stop() {{
    if [ ! -f "$PIDFILE" ]; then return 0; fi
    PID="$(cat "$PIDFILE" 2>/dev/null)"
    if [ -n "$PID" ] && kill -0 "$PID" 2>/dev/null; then
        echo "Stopping iroh-tunnel ($ROLE) (pid $PID)"
        kill -TERM "$PID" 2>/dev/null || true
        # Give iroh-tunnel up to 5s to drain on SIGTERM, then force-kill.
        i=0
        while [ "$i" -lt 5 ] && kill -0 "$PID" 2>/dev/null; do
            sleep 1; i=$((i + 1))
        done
        kill -0 "$PID" 2>/dev/null && kill -KILL "$PID" 2>/dev/null || true
    fi
    rm -f "$PIDFILE"
}}

status() {{
    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE" 2>/dev/null)" 2>/dev/null; then
        echo "iroh-tunnel ($ROLE) is running (pid $(cat "$PIDFILE"))"
        return 0
    fi
    echo "iroh-tunnel ($ROLE) is not running"
    return 3
}}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop; start ;;
    status) status ;;
    *) echo "Usage: $0 {{start|stop|restart|status}}"; exit 1 ;;
esac
exit $?
"#
    )
}

/// Mark `path` executable (0755). BusyBox init's rcS only runs scripts that
/// pass its `-x` test, so the bit is mandatory for boot autostart.
#[cfg(unix)]
fn set_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut perms = std::fs::metadata(path)
        .with_context(|| format!("failed to stat {}", path.display()))?
        .permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(path, perms)
        .with_context(|| format!("failed to chmod {}", path.display()))?;
    Ok(())
}

/// Bail unless running as root (uid 0). The init script lives under
/// `/etc/init.d` and writes a PID file under `/var/run`, so root is required.
/// Uses `id -u` to avoid a libc dependency just for getuid(2).
#[cfg(unix)]
fn require_root() -> Result<()> {
    let out = std::process::Command::new("id")
        .arg("-u")
        .output()
        .context("failed to run `id -u` to check privileges")?;
    let is_root = String::from_utf8_lossy(&out.stdout).trim() == "0";
    if !is_root {
        bail!(
            "installing a system service on this host requires root. \
             Re-run with sudo — BusyBox init installs under /etc/init.d."
        );
    }
    Ok(())
}

/// Run the installed init script with `verb` (start/stop/restart), bailing on a
/// non-zero exit. The script's shebang + executable bit let us invoke it
/// directly (same path busybox init uses on boot).
fn run_script(role: &str, verb: &str) -> Result<()> {
    let path = script_path(role);
    let status = std::process::Command::new(&path)
        .arg(verb)
        .status()
        .with_context(|| format!("failed to run {} {}", path.display(), verb))?;
    if !status.success() {
        bail!("{} {} failed with {status}", path.display(), verb);
    }
    Ok(())
}

pub fn install(role: &str, scope: ServiceScope, config: &Path) -> Result<()> {
    require_root()?;
    if scope == ServiceScope::User {
        eprintln!(
            "note: this host runs BusyBox init (no systemd); installing a \
             system-wide /etc/init.d script. BusyBox has no per-user services, \
             so --system is implied."
        );
    }
    let binary = resolve_binary()?;
    let script = format_script(role, &binary, config);
    let path = script_path(role);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    std::fs::write(&path, &script)
        .with_context(|| format!("failed to write {}", path.display()))?;
    set_executable(&path)?;
    // Start now. A start failure is surfaced, but the script is installed, so
    // the service will come up on the next boot regardless.
    run_script(role, "start")?;
    println!(
        "Installed and started {} at {}",
        script_name(role),
        path.display()
    );
    Ok(())
}

pub fn uninstall(role: &str, _scope: ServiceScope) -> Result<()> {
    require_root()?;
    let _ = run_script(role, "stop"); // best-effort: the service may not be running
    let path = script_path(role);
    if path.exists() {
        std::fs::remove_file(&path)
            .with_context(|| format!("failed to remove {}", path.display()))?;
    }
    println!("Uninstalled {}", script_name(role));
    Ok(())
}

pub fn start(role: &str, _scope: ServiceScope) -> Result<()> {
    require_root()?;
    run_script(role, "start")
}

pub fn stop(role: &str, _scope: ServiceScope) -> Result<()> {
    require_root()?;
    run_script(role, "stop")
}

pub fn restart(role: &str, _scope: ServiceScope) -> Result<()> {
    require_root()?;
    run_script(role, "restart")
}

pub fn status(role: &str, _scope: ServiceScope) -> Result<()> {
    let path = script_path(role);
    let status = std::process::Command::new(&path)
        .arg("status")
        .status()
        .context("failed to run init script status")?;
    // The script returns 3 when not running — informative, not a hard error
    // (mirrors how the systemd backend treats `systemctl status` of a stopped
    // unit), so don't bail on a non-zero exit here.
    let _ = status;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn script_name_has_boot_order_prefix() {
        assert_eq!(script_name("serve"), "S96iroh-tunnel-serve");
        assert_eq!(script_name("access"), "S96iroh-tunnel-access");
    }

    #[test]
    fn script_path_lives_under_init_d() {
        assert_eq!(
            script_path("serve"),
            PathBuf::from("/etc/init.d/S96iroh-tunnel-serve")
        );
    }

    #[test]
    fn format_script_embeds_paths_and_all_verbs() {
        let s = format_script(
            "serve",
            Path::new("/usr/local/bin/iroh-tunnel"),
            Path::new("/etc/iroh-tunnel/serve.toml"),
        );
        assert!(s.starts_with("#!/bin/sh"), "must start with sh shebang");
        assert!(s.contains("DAEMON=\"/usr/local/bin/iroh-tunnel\""), "{s}");
        assert!(s.contains("CONFIG=\"/etc/iroh-tunnel/serve.toml\""), "{s}");
        assert!(
            s.contains("PIDFILE=\"/var/run/iroh-tunnel-serve.pid\""),
            "{s}"
        );
        assert!(s.contains("LOG=\"/var/log/iroh-tunnel-serve.log\""), "{s}");
        // The daemon invocation passes the role through the ROLE variable
        // (interpolated once into ROLE="…" above) — not a per-role literal.
        assert!(
            s.contains("\"$DAEMON\" \"$ROLE\" run --config \"$CONFIG\""),
            "daemon invocation wrong: {s}"
        );
        // All four init verbs must be wired in the case block.
        for arm in [
            "start) start",
            "stop) stop",
            "restart) stop; start",
            "status) status",
        ] {
            assert!(s.contains(arm), "missing case arm `{arm}`:\n{s}");
        }
    }
}
